spring.application.name=hello


spring.datasource.url=jdbc:postgresql://localhost:5432/practicedb
spring.datasource.username=postgres
spring.datasource.password=Manikandan123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=Mani
spring.security.user.password=1234